### PR TITLE
Fix EFS volumes if already exists

### PR DESCRIPTION
**Pull request by anthonymq**

### CODE REVIEW

**Comment by mxab** [comment]
Hi, thank you contributing to this project. Could you elaborate a bit more about all the changes

**Comment by anthonymq** [comment]
Hi @mxab,
I'm using your spawner since we have a nomad cluster in production. I encountered an issue with AWS EFS volumes. 
The AWS efs csi driver returns an error if a volume already exist which is pretty annoying.
This fix catches that error since creating a volume should not return an error if it already exist.

**Comment by mxab** [comment]
Hi,
yes I guess this makes sense. Thank you for cleaning up the PR

**Comment by mxab** [comment]
It's released. Thanks for contributing

**Pull request merged**
